-- Add is_telematics_only flag to service_plan_units.
-- Rows where repairUnitId starts with 'telematics-' are the legacy synthetic IDs
-- and should be marked as telematics-only. New telematics-only rows will get a
-- stable cuid() as repairUnitId (generated by the app) and this flag set to true.

ALTER TABLE service_plan_units
  ADD COLUMN IF NOT EXISTS is_telematics_only BOOLEAN NOT NULL DEFAULT false;

-- Backfill existing synthetic-ID rows
UPDATE service_plan_units
  SET is_telematics_only = true
  WHERE repair_unit_id LIKE 'telematics-%';
